#!/bin/bash
DESTDIR="$HOME/Pictures/screenshots/${HOSTNAME}"
FILENAME=""

if [ ! -d "${DESTDIR}" ]; then
    mkdir -p "${DESTDIR}"
fi

DATE=$(date +"%m.%d.%y-%H:%M:%S")

if [[ ! -n $1 ]]; then
    FILENAME="${DESTDIR}/${DATE}.png"
    import "${FILENAME}"
else
    if [[ $1 = "root" ]]; then
        FILENAME="${DESTDIR}/root-${DATE}.png"
        import -window root "${FILENAME}"
    elif [[ $1 = "active" ]]; then
        WINDOWID=$(xdotool getactivewindow)
        WINDOWNAME=$(xdotool getactivewindow getwindowname)
        FILENAME="${DESTDIR}/${WINDOWNAME}-${DATE}.png"
        import -window "${WINDOWID}" "${FILENAME}"
    fi
fi

xclip -selection clipboard -t image/png -i "${FILENAME}"
